name: ğŸ”‚ Surge PR Preview

on:
  pull_request:
    # when using teardown: 'true', add default event types + closed event type
    types: [opened, edited, synchronize, reopened, closed]
  push:

jobs:
  preview:
    environment: surge # link to the environment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # allow surge-preview to create/update PR comments
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to surge
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: build
          failOnError: 'true'
          teardown: 'true'
          build: |
            npm ci
            npm run build

      - name: Surge preview URL
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"